### ISSUE TITLE
dt.exe returns 0 even when documents have failed to transfer

### ISSUE THREAD

**Issue by quanticle** [Azure/azure-documentdb-datamigrationtool#10]
I'm scripting some bulk inserts into DocumentDb using dt.exe and I've noticed that dt.exe returns 0 even when some documents have failed to transfer. To reproduce this issue, create a JSON file with invalid syntax and try to upload it to DocumentDb. dt.exe will print out that the document failed to transfer, but will still return 0, indicating success. The more appropriate behavior would be to return the number of documents that have failed to transfer, leaving it up to the caller to decide whether it's okay to ignore failures or not.

**Comment by nahk-ivanov** [comment]
I would like to get more details on the scenario. Do you really need to get the number of failed documents as a return code? I would like to use return code to identify the type of failure (as it meant to be), so that consumer can distinguish between "soft" failure (few documents were not inserted because of the duplicate ID, for example) vs. tool crashing with unhandled exception/invalid user input.
If we will just return non-zero code from the tool on some documents failed to insert, will that be sufficient to cover your scenario?

**Comment by quanticle** [comment]
Returning an error type would be fine as well. The number of failed documents was an example (apologies if that wasn’t clear). The problem I have is that I’m scripting dt.exe to upload a bunch of JSON documents to DocumentDB, and currently I can’t tell if any documents failed without parsing the output of the tool. Any non-zero return code would be sufficient for my use case.

**Comment by nahk-ivanov** [comment]
Got it! We will add return code support on "soft" failures in one of the future versions. For now it could be easier for you to just specify an error log file and check if it's empty or not, instead of parsing an output.

**Comment by nahk-ivanov** [comment]
Resolved in 12dee7c3f05cb0b5e4bf540dba4645ba87f265ad. Tool now returns `-10` when some of the documents failed and `-1` in case of critical failure.

**Comment by ghost** [comment]
I am finding that as of 1.7, dt.exe returns 0 if a completely invalid DatabaseName is specified in the connection string.

**Comment by nahk-ivanov** [comment]
Hello,

If non-existing database name is specified in the target connection string - it will be created.

If non-existing database name is specified in the source connection string - it will treat it as no documents to import.

This was the decision we made long ago and, even though, it was questioned a few times since then - it happens on a very rare occasion, so most of the customers are okay with such behavior and it fits their scenario. We do understand that sometimes you would prefer it to fail, if source database/collection does not exist. In that case I'd suggest you to use DocumentDB .NET SDK from PowerShell and check for the database before kicking off the import. I have a sample for that [here](https://github.com/Azure/azure-documentdb-datamigrationtool/issues/11#issuecomment-212152277).

Regards,
Alex.

**Comment by ghost** [comment]
Thanks for your response Alex!

If non-existing target blob is specified in the /t.File:blobs:// location - an exception will be thrown and a non-zero code returned.  

I would prefer a deterministic behavior for the scenarios where sources or targets do not exist.  It's somewhere in the middle right now.

Perhaps if a non-existing database name is specified in the target then it fails unless a "t.CreateIfNonExistent" flag is set.

**Comment by nahk-ivanov** [comment]
Hi,

If non-existing target BLOB is specified - it will be created. This is the only way to export to BLOB without providing /t.Overwrite switch.

If non-existing storage container is specified, it will be created as well.

If non-existing storage account is specified, then tool will fail, as it cannot create the storage account with the given credentials (where would you get an Account key at first place?). It would require us to access your Azure subscription and create a storage account through RM APIs.

In the case of DocumentDB, if you specify DocumentDB account that does not exist - tool will fail. This is the same as storage account and would require us to get access to your Azure subscription. DocumentDB database and collection map to storage account container and BLOB path. All of these entities are being created by the tool.

Regards,
Alex.

**Comment by peterjohnsonme** [comment]
I appreciate it.  I am using this tool in an automated environment to perform backups in lieu of an Azure-provided solution, and I'm trying to limit the situations that can result in a false success.
