### ISSUE TITLE
When importing a CSV file with a field whose value is '8-15' it gets converted to a date time

### ISSUE THREAD

**Issue by kristan66** [Azure/azure-documentdb-datamigrationtool#107]
When importing a CSV file with a field whose value is '8-15' it gets converted to a date time string in Cosmos.  Seems like a bug?

**Comment by nahk-ivanov** [comment]
Looking at the code it seems to be "by design". If you look at line 74 of [CsvReader.cs](https://github.com/Azure/azure-documentdb-datamigrationtool/blob/cbb2d3f880fe91b6aca6b3c2cc00590565ffc290/CsvFile/Microsoft.DataTransfer.CsvFile/Reader/CsvReader.cs#L74) you should be able to quote your values and they will be treated as strings.

There is a type inference logic in [ConvertUnquotedValue(...)](https://github.com/Azure/azure-documentdb-datamigrationtool/blob/cbb2d3f880fe91b6aca6b3c2cc00590565ffc290/CsvFile/Microsoft.DataTransfer.CsvFile/Reader/CsvReader.cs#L132), which is there on purpose, so it's hardly a "bug". Without it all values would be moved as strings, which is not an expected behavior for majority of the users (you probably still want your unquoted numbers to be moved as integers and floats). Your issue does seem to be a corner-case where it parses as an (unwanted) valid date value. We can probably introduce gazillion of configuration options in one of the future versions, including user-provided schema, but it's not even on the backlog, as this is the first time in over 4 years we hit this problem.

You can just fork the repo and modify ```CsvReader``` according to your needs.
