### ISSUE TITLE
JSON import and MONGODB export different formats for dates

### ISSUE THREAD

**Issue by debaldwi** [Azure/azure-documentdb-datamigrationtool#16]
You can select "EPOCH only" for both and you will get different output. The difference in this output happens to break queries to DocDB. 

JSON output for date: 

"Timestamp": {
      "$date": 1439488954
    },

Mongo output for date: 

"Timestamp": 1439514154,

Can you tell me how to fix this?

**Comment by nahk-ivanov** [comment]
Hello,

Can you please explain a little bit more what you are trying to achieve? If you are trying to import a mongoexport JSON file you will need to select an appropriate source in the tool: `MongoDBExport` for command line or `MongoDB export (mongoexport) JSON file(s)` in the UI version. If you will use standard JSON import when importing mongoexport files you might end up with lots of internal information in your DocDB collection, as mongoexport JSON files contain some metadata associated with fields (property type being one of them).

To your particular example:

```
"Timestamp": {
    "$date": 1439488954
},
```

in mongoexport JSON file means that there is a property `Timestamp` of type `datetime`. Since DocDB does not have native support for `datetime`, in the tool we allow you to specify how you want to preserve it in the target DocDB collection: epoch integer, string, or both. Based on this selection you will have different format for your `Timestamp` property in DocDB collection. Please refer to [this article](https://azure.microsoft.com/en-us/blog/working-with-dates-in-azure-documentdb-4/) for more information. You will have to adjust your queries based on the selection.

Anyway, if you can explain your scenario we may come up with a proper solution.

Regards,
Alex.

**Comment by debaldwi** [comment]
So here is what I do, for some systems, I have to mongoexport a collection. Then use DT to import that. That is when I get the above, 

"Timestamp": {
    "$date": 1439488954
},

However, on other systems, I'm able to just hit the db directly. This is the same DB schema, so that isn't the issue. When I hit the system directly, I get: 

"Timestamp": 1439514154,

I have confirmed with the same db and both methods. Shouldn't dt.exe modify this $date, like it does with hitting mongo directly? 

=Devon

**Comment by nahk-ivanov** [comment]
Hello,

Yes, dt.exe should modify $date. I just tested latest (1.6) version with your sample:

**mongosample.json**

```
{ "Timestamp": { "$date": 1439488954 } }
```

With the following dt.exe command line:

`/s:MongoDBExport /s.Files:mongosample.json /t:DocumentDB /t.ConnectionString:xyz /t.Dates:Epoch /t.Collection:mongotest`

And got the following document in my DocumentDB collection:

```
{
  "Timestamp": 1439489,
  "id": "c26a243c-bc50-45e2-94b2-753599e895ec"
}
```

Can you please double check if you are using the right source (`/s` argument)? It should be `MongoDBExport` when working with mongoexport JSON files.

Regards,
Alex.

**Comment by debaldwi** [comment]
Ahh I think I’m using 1.2 I’ll double check today.
