### ISSUE TITLE
Support for Arrays

### ISSUE THREAD

**Issue by ijabit** [Azure/azure-documentdb-datamigrationtool#26]
When I'm importing from SQL Server, I can specify a nesting separator to nest objects. However, that won't work for nested collections. For example, if I wanted to import an Order with all OrderDetail records in an array, I can't figure out how to construct that JSON document using this tool. Am I missing something?

**Comment by nahk-ivanov** [comment]
Hi,

You will have to write a custom transformation function as explained in [this article](https://azure.microsoft.com/en-us/blog/easily-transform-data-when-importing-to-azure-documentdb-2/).

This is only supported for bulk import (non-partitioned collections). I believe you already requested to support triggers, which hopefully will resolve this for sequential import as well.

Regards,
Alex.

**Comment by ijabit** [comment]
Thanks for the quick response! The article you posted does work for simple properties. My example is OrderDetail records, which would be an array of objects with many properties. It would be nice for the tool to integrate with the FOR JSON capability built into SQL 2016. That way I could just do a sub-select, format FOR JSON, and the tool could put that array into my document, rather than going through all of that work with a trigger/stored procedure. This is a good work-around though, and combined with FOR JSON I think I can make it work.

**Comment by nahk-ivanov** [comment]
Hi,

Yeah, I agree, that would be nice. The problem is that there is no new data type for the JSON in SQL Server, it's still represented as an NVARCHAR and clients have no context whether you want it as a JSON string or a proper object.

We had an idea to allow user to specify a set of columns that should be treated as raw JSON and converted to objects during data movement, but then settled on the transformation function, which covers more scenarios. At that time there were no partitioned collections, though, and bulk import was the preferred way. We may revisit that idea now, given that sequential import is the only one supported for partitioned collections.

As of today, I think you can format your JSON in the SQL Server using new built-in functions and then use transformation stored proc with eval() to make it an array of objects.

Regards,
Alex.

**Comment by ijabit** [comment]
The last time i tried using Eval it said it wasn't supported in a trigger/sproc.

**Comment by AndrewHoh** [comment]
Instead of eval(), you can run JSON.parse(). Ex: JSON.parse('{\"foo\": \"bar\"}')

**Comment by ijabit** [comment]
@AndrewHoh thanks!!

**Comment by ijabit** [comment]
I tried it and JSON.parse() worked great for bulk upload! But until triggers are supported in the tool, we still can't do this for partitioned collections. So I'll leave the issue open for the time being. Is there any other workaround for partitioned collections?

**Comment by ijabit** [comment]
@AndrewHoh Unfortunately when using the JSON.parse() method in a transform, we don't get the automatic object expansion based on the nesting separator. Meaning that I'd have to write a whole bunch of transformation logic to expand based on the nesting separator, duplicating all of the logic that this import tool already does for us. @nahk-ivanov I think your idea of having the user specify fields which the tool could auto-parse into JSON is much better because you could re-use all of your existing logic to expand out objects based on the nesting separator.

**Comment by nahk-ivanov** [comment]
@ijabit but you only need to do JSON.parse() for one field, that comes in as a "stringified" JSON. The nesting separator is being applied in the tool, so by the time it hits the transformation function in the stored proc - you already have all the simple nested fields separated and all you need is to JSON.parse the values of a few fields that you crafted as a JSON string at the source.
Even if we will auto-parse the fields in the tool, we will not expand anything, as it should be a valid JSON already and if the field happens to have a name "My.Field", then it will be { "My.Field": null }, instead of { "My": { "Field": null } }. If we expect field to come in as a JSON string, then we expect it to be proper nested JSON already. The nesting separator was added to the tool to allow a little bit more complex scenarios when importing from flat table data sources.

**Comment by ijabit** [comment]
@nahk-ivanov

> we expect it to be proper nested JSON already

I didn't think that SQL Server could format "My.Field" as a nested object but I just found that you can use FOR JSON PATH which should essentially do what the tool was doing for me. I think FOR JSON PATH will work for SQL Server.
