### ISSUE TITLE
DocumentDB Import Speed

### ISSUE THREAD

**Issue by ijabit** [Azure/azure-documentdb-datamigrationtool#28]
I'm importing 20 million records into DocumentDB and the import is a bit slow. I'm getting about 1 million records in 30 minutes. I changed my default consistency level to Session, but that didn't make much difference.

I put the following code into DocumentDbClient.cs:
```
        public async Task<StoredProcedureResult<TResult>> ExecuteStoredProcedureAsync<TResult>(string storedProcedureLink, params dynamic[] args)
        {
            var time = DateTime.Now;
            var result = await client.ExecuteStoredProcedureAsync<TResult>(storedProcedureLink, args);
            var elapsed = DateTime.Now.Subtract(time).TotalMilliseconds;
            System.Diagnostics.Debug.WriteLine($"DocDb: {elapsed}ms");
            return new StoredProcedureResult<TResult>(result.ActivityId, result.Response);
        }
```
I increased the batch size to 500 and got the following results:
```
DocDb: 1133.773ms
DocDb: 963.2317ms
DocDb: 1207.7909ms
DocDb: 1171.7819ms
DocDb: 1283.8086ms
DocDb: 1290.8112ms
DocDb: 1037.2496ms
DocDb: 1044.2515ms
DocDb: 1137.7737ms
DocDb: 998.7406ms
DocDb: 1050.252ms
DocDb: 977.2348ms
DocDb: 840.7023ms
DocDb: 856.2063ms
```
Almost all of the time taken during the import is not the retrieval of the SQL Server data, but on the execution of the DocumentDB stored procedure. I've had similar results on a different 3 million record import. Is there any way to increase the speed of the bulk import stored procedure? Or is this time just the standard amount of time that DocumentDB takes to perform 500 upserts?

**Comment by nahk-ivanov** [comment]
Hi,

Well, batch size does not always translate to the number of documents beeing inserted at one round trip to the server. There is a request limit of about 2 or 4 MB (I don't remember from the top of my head), and if documents don't fit in 1 request - the tool will do as much as possible, but less.

Then you should check what you collection throughput is and make sure you are not being throttled.

You may be able to find more support with this on the customer connect forum, rather than through an issue for the tool on github.

Regards,
Alex.

**Comment by ijabit** [comment]
These documents are only about 500 bytes, very small. And the batch size doesn't seem to be affecting the overall time. I tried the default 50 batch size and 500, and about the same time for import on both. The collection is the max of 10,000 RU/s, so that's not it either.

I would think that DocumentDB would be able to write millions of records in an extremely fast manner so my conclusion is that there may be something in this tool's stored procedure slowing things down.

**Comment by AndrewHoh** [comment]
Hi @ijabit, can you share your DocumentDB account/database name? Let me look into our telemetry to see if I can root cause the issue.

**Comment by ijabit** [comment]
Hi @AndrewHoh. I sent the name to the gmail address listed on your GitHub profile. Thanks!

**Comment by ijabit** [comment]
@AndrewHoh were you ever able to reproduce this?

**Comment by AndrewHoh** [comment]
Hi @ijabit, we've root caused the issue and it's mostly due to not having the optimal batch size for the import. Depending on your document sizes and RU charges, we would need to produce the optimal batch size that would complete with minimal throttling.

**Comment by ijabit** [comment]
@AndrewHoh I don't understand how that could be the case? When we were troubleshooting, we tried increasing the batch sizes to 50, 100, 1000, 10000, even 100000 I think. The RU's for the collection were at max, and I wasn't getting throttled until we increased the batch size extremely high and we changed the number of threads to a high number.

**Comment by ijabit** [comment]
@AndrewHoh any update or guidance on this issue? I've tried all types of batch sizes and it doesn't seem to help.

**Comment by AndrewHoh** [comment]
@ijabit We have found that there is room for improvement with the tool, especially related to the batch import support. We would recommend going with the sequential record import with an increased number of parallel threads, while we work on the performance improvements of the tool.

**Comment by ijabit** [comment]
@AndrewHoh Thanks for looking at this and improving the import process. Unfortunately, I can't use sequential import since the tool doesn't support triggers and I need to modify the data as it gets imported. Do you have an alternative way to run a transform on the data while doing a sequential import?

**Comment by nahk-ivanov** [comment]
Hi @ijabit,

For that we were thinking since you already got the source code and was able to build and run it, maybe you can just modify the documents in the tool's code itself, before inserting them? In the [DataItemJsonConverter.cs](https://github.com/Azure/azure-documentdb-datamigrationtool/blob/6ab27d8eaf3ef30217e627ac8c6ab58f2fa0302f/Shared/Microsoft.DataTransfer.JsonNet/Serialization/DataItemJsonConverter.cs#L74) on the line 74 you can check the filedName to be one having a JSON string and instead of serializing the value to a string, just write it raw to the writer.

Regards,
Alex.

**Comment by ijabit** [comment]
@AndrewHoh @nahk-ivanov Even with sequential import the speed of an import is brutally slow. I can export all records out of DocDB in < 10 mins, but it takes 2 hours to import them. Has anyone looked at this again?
