### ISSUE TITLE
Support Cosmos DB Bulk Executor import

### ISSUE THREAD

**Issue by Greybird** [Azure/azure-documentdb-datamigrationtool#64]
### Issue
When I want to Bulk Import data to a Cosmos DB partitioned collection, I'm getting a error stating that I should supply a PartitionKey, preventing me to insert data using the bulk feature.
As stated in #47, this is actually unsupported by the bulk mechanism currently implemented.

### Solution Proposal
I discovered reading https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started that Microsoft published [Microsoft.Azure.CosmosDB.BulkExecutor](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/) nuget which supports working with partitioned collections.
My initial tests show that this is actually working fine in my target scenario.

### Prerequisites
The library is only supporting .Net 4.5.2, so the project should be upgraded (WIP on #63)
Note that the nuget package incorrectly uses net451 directory for the library

### Implementation
I would like to integrate the BulkExecutor into the tool, but have a few questions:

#### Add or Replace 
Should I consider this integration a replacement for the previous bulk import feature, or a new import method (EnhancedBulk - or better name)?

#### Split of data in batches
The `BulkExecutor`:
* is fed with an `IEnumerable`, its internals taking care of the batch split of the collection
* only reports statistics at the end of a bulk import session, and not while importing (no callback, and source code is not available to add this feature)

Handling the split in batches of items outside of the BulkExecutor:
* on the pro side, would allow the tool to use the same kind of approach for progress reporting
* on the con side, might however have unwanted consequences on performances of the import

I would usually be more in favor of letting the `BulkExecutor` handle this task, especially as it has settings to control the batch sizes.
However, this will make the tool blind on progress, until the end of the session, and the implementation is consuming the enumerable before starting the import, which kind of defeats the `IEnumerable` purpose.
So I would tend to implement a split outside the executor.

Do you have a view on this?

#### Reporting of statistics
Currently, items are reported as transferred as soon as they are written to the destination sink.

The current bulk import feature is working around this by registering a `TaskCompletionSource` for each item into a collection, and blocking the `WriteAsync` until a batch has been processed.
Considering the batch size is of a reasonable size (default is 100), this is working well.

I'm not sure using the same approach for the BatchExecutor is the correct way to go, as the size of batch will probably be significantly bigger (10,000 / 100,000) to take advantage of `BulkExecutor` load distribution.

Do you have a view on how to handle this?

Regards,

**Comment by nahk-ivanov** [comment]
Hi,

As you may already know, current bulk import works by creating a temporary stored procedure that accepts array of documents and inserts them internally on the server, therefore eliminating extra network round-trips for each single document.
The problem with partitioned collections was that you would need to create stored procedures in every collection and perform partitioning on the client-side, to make sure you call procedure in the right collection. Not that we can't do it, we just never got to it and you could already use single-document import mode and increase number of parallel requests.

It seems like `BulkExecutor` is the same thing, but it uses some built-in stored procedures and gives you .NET wrapper that does client-side partitioning. This is similar to the logic we were planning to do in the tool itself, but since you can just use "off the shelve" `BulkExecutor` for this - I think it should be the way to go.

As to the tasks - there is indeed some performance penalty for doing it this way, but it shouldn't be that bad, if logical `TaskCompletionSource` is used, as opposed to the actual thread-based parallelism. The reason why we decided to go with this approach was to simplify sinks implementation - you only have to implement a simple insert operation and infrastructure will take care of the rest for you - parallelism, statistics, error handling, etc. We could just pass `IEnumerable` to the sink directly and let it handle everything, but then every sink author will have to take care of these fundamental things himself. This is a usual trade-off between _point-to-point_ solution vs. generic approach: _point-to-point_ will always be faster. We could even get rid of the `IDataItem` interface to eliminate thousands of allocations, but we will lose generalization and "any source to any sink" compatibility.
`BulkExecutor` appears to be a "point-to-point" solution, which, while faster, might be hard to integrate into generalized solution.

With that in mind, if we agree that to make our solution generic enough to fit in the tool we will have to sacrifice some performance, I think we can do this:

- Accumulate up to _X_ documents within the sink itself (this can be configurable)
- Return logical task for each input document, as current bulk import does (maybe we can reuse old instances somehow to eliminate extra allocations?)
- Feed this chunk to `BulkExecutor` and resolve tasks once it's done

This is almost the same as original bulk insert, but uses `BulkExecutor` API instead of calling the stored procedure directly. Of course, it will be slower than a custom tool that just uses `BulkExecutor` directly, without reporting any progress or support for multiple different sources, but you have to pay the tax for that convenience.

Alternate solution could be to reverse-engineer what `BulkExecutor` does: primarily which stored procedure is being called, what inputs it expects and how client-side partitioning is implemented to match that of a server. Then you can reuse the same thing directly from the tool and get proper reporting and potentially smaller batches (less `Task`s). Better yet - just use our custom stored procedure and basically make existing bulk import to work with partitioned collections. This has an extra benefit, because it allows you to perform document transformation as part of the import.

Another interesting thing about `BulkExecutor` (or any other parallel insertion mechanism, for that matter) is that your source data should be _shuffled_ by partition key. That's it - documents should be arriving in random order to make sure we can insert into different partitions, rather than bombarding a single one. I think at some point this may give you more performance impact, than trying to optimize infrastructure within the tool.

Regards,
Alex.

**Comment by Greybird** [comment]
Hi @nahk-ivanov,

Thanks a lot for this very detailed answer!
I will take a deeper look at the insides of `BulkExecutor` to try to find the best way to go, using your valuable insights as a guidance.

I will update this issue based on my findings.

Regards,
